# Specifying the Docker Compose file format version
version: '3'

# Definition of all services
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - app-data:/app/data

# Definition of all volumes
volumes:
  # nodemodules volume (it will be created if it doesn't exist)
  app-data:  
