# Specifying the Docker Compose file format version
version: '3'

# Definition of all services
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Use a named volume "nodemodules" and bind it to /app/node_modules in the container
      - nodemodules:/app/node_modules

# Definition of all volumes
volumes:
  # nodemodules volume (it will be created if it doesn't exist)
  nodemodules:  
